### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by MiroslavMikus** [tmoreno/open-log-viewer#1]
Hi,
is there a way to get implemented some search logic??
Something like [Lucene](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)?

Thank you in advice

**Comment by tmoreno** [comment]
Hi!

There are some methods to perform search using the Electron API:

https://github.com/electron/electron/blob/master/docs/api/web-contents.md

At the moment, I'm planning to change how to load the log file into the view to can use those functions.

I would like to use [Ace](https://ace.c9.io/) or other similar library.

Thanks for you comment! :)

**Comment by tmoreno** [comment]
Hi Miroslav,

I've just published a new version with search feature.

Press Ctrl+F or Command+F to open search bar.

Cheers!

**Comment by MiroslavMikus** [comment]
Hi @tmoreno,

thank you for your response :)

I'm definitely going to take a look at this feature
