### ISSUE TITLE
Is there any plan that release on Archlinux?

### ISSUE THREAD

**Issue by tan-wei** [tmoreno/open-log-viewer#13]
After several times failing install by npm, I wonder that is there any further plan. Thanks!

**Comment by tan-wei** [comment]
After another try. I can successfully built it with `npm`. Previous failure is related to bad network and missing installation of `gconf`.

**Comment by tmoreno** [comment]
Hi Wei!

I'm pleased you could run the app on your system.

There are some builds in the repo that you can install on the most popular Linux distros, but I don't know if they are compatible with Archlinux

https://github.com/tmoreno/open-log-viewer/releases/tag/1.4.0

I'll close the issue
