### ISSUE TITLE
Use from terminal

### ISSUE THREAD

**Issue by yelsayd** [tmoreno/open-log-viewer#15]
I usually get logs through a terminal command, it'd be nice if I can do `log-viewer <filepath>` in shell directly. The Finder browser is also pretty limited.

**Comment by tmoreno** [comment]
Hi Yasser,

I've just released a new version with your suggestion:

https://github.com/tmoreno/open-log-viewer/releases/tag/1.5.0

Thanks for you feedback!

Regards

**Comment by yelsayd** [comment]
Sweet! Thanks @tmoreno.
