### ISSUE TITLE
If a line starts with more than 4 spaces the line is whited

### ISSUE THREAD

**Issue by aureleS** [tmoreno/open-log-viewer#16]
I think it is caused by the tab separator after fourth space to show a tab.
[testlog.log](https://github.com/tmoreno/open-log-viewer/files/4798557/testlog.log)

**Comment by tmoreno** [comment]
Hi Aurele,

I've just fixed the bug reported by you

https://github.com/tmoreno/open-log-viewer/releases/tag/1.4.1

Please, check if the problem is solved.

Thanks for your contribution!

**Comment by aureleS** [comment]
Hi Thomas, 
it works fine, thanks !
