### ISSUE TITLE
New log lines get inserted at cursor

### ISSUE THREAD

**Issue by AaronAsAChimp** [tmoreno/open-log-viewer#18]
Expected Behavior:
New log lines are added at the end of the log file display.

Current Behavior:
New log lines are added at the text cursor.

Steps to Reproduce:
1. Open a log file that is being continuously appended to.
2. Click on a line that is not the last line or select some text.
3. Wait for the next display update.
4. Observe that the new lines are added at the cursor position replacing any text that is selected.

**Comment by tmoreno** [comment]
Hi Aaron,

I've just released a new version of the app with the bug fixed: 

https://github.com/tmoreno/open-log-viewer/releases/tag/1.4.2

Please, cloud you check if the bug is fixed for you?

Thanks for you feedback!

**Comment by AaronAsAChimp** [comment]
Thank you, it works great!
