### ISSUE TITLE
Chrome and Edge warning during download and Windows 10 warning when opening the program

### ISSUE THREAD

**Issue by mickdewald** [tmoreno/open-log-viewer#19]
Something seems to be not right. The browser as well as the OS warns me about the program, that there might be something harmful in this application. Unfortunately and can't say more about the topic.

**Comment by tmoreno** [comment]
Hi!

I'm signing the Windows version with a self-signed code certificate, so I it's normal that browsers and Windows alert to you in some way.

A valid certificate cost money, I don't know how much, so I won't buy any, at the moment.

Do you know if I can get one for free?

Thanks for you feedback!

**Comment by mickdewald** [comment]
Unfortunately I haven't found any CA that supplies free certificates for open source projects. That is really a shame. The cheapest one are for about 100 USD per year.

**Comment by tmoreno** [comment]
I close this issue because is related with Microsoft Certificates
