### ISSUE TITLE
Change Text size?

### ISSUE THREAD

**Issue by ahmednrana** [tmoreno/open-log-viewer#2]
Hi, Thanks for the brilliant tool is there any way to change / customize the fonts and their sizes?

**Comment by tmoreno** [comment]
Hi!,

No at the moment, I would like to change how the log file is loaded on the view and I'm doing some tests with [Ace](https://ace.c9.io/)

I take note from your suggest, and I will added it in a future version.

Thanks! :)

**Comment by tmoreno** [comment]
Hi!

I've recently released a new version that allows change the font size.
