### ISSUE TITLE
Add feature to automatic scrolling

### ISSUE THREAD

**Issue by hendrakwong** [tmoreno/open-log-viewer#3]
The application needs the ability to automatically scroll to the last log. Also, provide a way to enable/disable this feature.

**Comment by tmoreno** [comment]
Hi Hendra!

Now I'm trying to integrate Ace Editor, because it provides some interesting features like search.

The automatic scrolling is a feature that I already had planned, but it will have to wait for a while.

Thanks for your feedback :)

**Comment by tmoreno** [comment]
Hi Hendra,

Finally, I've just released a new version with the feature that you suggested:

https://github.com/tmoreno/open-log-viewer/releases/tag/1.5.0

Sorry for the delay :P

Cheers!

**Comment by hendrakwong** [comment]
Thank you for the support. I'll check it out.

**Comment by tmoreno** [comment]
Can I close the issue?
