### ISSUE TITLE
Persisted global settings

### ISSUE THREAD

**Issue by hendrakwong** [tmoreno/open-log-viewer#4]
The ability to persist the global settings so the user does not have to change the modified settings.

**Comment by tmoreno** [comment]
Settings are for each file, because you can open log files with different layout, but I have some troubles integrating Ace Editor and maybe setting will became global to all files.

**Comment by tmoreno** [comment]
Hi Hendra,

I've just published a new version that persist settings globally instead of by file.

Cheers!

**Comment by hendrakwong** [comment]
Thanks for adding this feature!
