### ISSUE TITLE
Ability to perform drag and drop log file to open the file

### ISSUE THREAD

**Issue by hendrakwong** [tmoreno/open-log-viewer#5]
The ability to perform "drag and drop" log file to open the file.

**Comment by tmoreno** [comment]
You can drag and drop a file when the tab does not have a file loaded.
Maybe drag and drop should works too with tabs with files loaded.

**Comment by tmoreno** [comment]
Hi Hendra,

Do you have the same problem with the latests releases?

**Comment by hendrakwong** [comment]
I am able to drag and drop a file now. Thanks for adding this functionality.

**Comment by tmoreno** [comment]
😄
