### ISSUE TITLE
Does it support log4j xml format?

### ISSUE THREAD

**Issue by hanabi1224** [tmoreno/open-log-viewer#6]
Thanks

**Comment by tmoreno** [comment]
Hi!

This weekend I've fixed two bugs, try to use the last one: 

https://github.com/tmoreno/open-log-viewer/releases/1.1.2

If you still having errors, please, attach a example file, but you should view log files generated by log4j.

Thanks for your feedback! :)

**Comment by hanabi1224** [comment]
@tmoreno Awesome, will have a try, thanks!

**Comment by tmoreno** [comment]
Hi!

The problem was solved?

I would like to close the issue
